---
title: "Data Manipulation"
output: github_document
---

```{r}
library(tidyverse)
```

Load the litter dataframe
```{r}
litters_df = 
  read_csv("data/FAS_litters.csv")

litters_df = janitor::clean_names(litters_df)

litters_df
```

Load the pups dataframe
```{r}
pups_df = 
  read_csv("data/FAS_pups.csv")

pups_df = janitor::clean_names(pups_df)

pups_df
```

## `select`

`select` is used to select columns!

```{r}
# order matters, and the colon allows you to select from one variable to another
select(litters_df, group, litter_number, gd0_weight)

select(litters_df, gd0_weight, group)

select(litters_df, group, gd0_weight:gd_of_birth)

select(litters_df, group, starts_with("pups"))

select (litters_df, -litter_number)

select(litters_df, -starts_with("gd"))

select(litters_df, group, litter_id = litter_number)

select(litters_df, litter_id = litter_number, everything())

select(litters_df, gd0_weight, everything())

```

These basically do the same thing
```{r}
rename(litters_df, litter_id = litter_number)

relocate(litters_df, litter_number)
```


`select` vs `pull`

```{r}
select(litters_df, group)

# this pulls it out of a dataframe and turns it into a vector; may have its pros or cons depending on the situation
pull(litters_df, group)
```

## Learning Assessment

```{r}
select(pups_df, litter_number:pd_ears)
```



## `filter`

get rid of rows using filter 

```{r}
# one equal sign says to put this variable into another variable and 2 equal signs basically asks to check whether these things are true

filter(litters_df, group == "Con7")

filter(litters_df, group == "Mod8")

filter(litters_df, group !="Con7")

filter(litters_df, gd0_weight > 20)

filter(litters_df, gd0_weight <= 20)

# # containing only those rows where the "group" column matches either "Con7" or "Con8"
filter(litters_df, group == "Con7"| group == "Con8")

# another way to get only those rows where the "group" column matches either "Con7" or "Con8"
filter(litters_df, group %in% c("Con7", "Con8")
       

filter(litters_df, !(group ="Con7")
       
# 2 conditions must be met for it to be in the filter
filter(litters_df, group %in% c("Con7", "Con8"), gd0_weight > 0)

# Learning Assessment 
filter(pups_df, sex == 1)

filter(pups_df, pd_walk < 11, sex == 2)
```

what about missing rows?

```{r}
# you can drop everything missing or just by column
drop_na(litters_df)
drop_na(litters_df, gd0_weight)
```



## `mutate`

this is used to add or change variables

```{r}
view(mutate(litters_df, wt_gain = gd18_weight - gd0_weight))

mutate(litters_df, group = str_to_lower(group))

# you can do multiple mutates in the same fxn
mutate(
  litters_df,
   wt_gain = gd18_weight - gd0_weight,
   group = str_to_lower(group)
  )
```


## `arrange`

```{r}
arrange(litters_df, gd0_weight) # ascending order

arrange(litters_df, group, gd0_weight)

```

## pipes 

```{r}
litters_df = 
  read.csv("data/FAS_litters.csv") |> 
  janitor::clean_names() |> 
  select(-starts_with("pups_survive")) |> 
  mutate(
    group = str_to_lower(group), 
    wt_gain = gd18_weight - gd0_weight,
    ) |> 
    drop_na(gd0_weight) |> 
    arrange(group, wt_gain)
```

