---
title: "Tidy data"
output: github_document
---

```{r}
library(tidyverse)
```

## PULSE data

```{r}
pulse_df=
  haven::read_sas("data/public_pulse_data.sas7bdat") |>
  janitor::clean_names() |>
  pivot_longer(
    bdi_score_bl:bdi_score_12m, 
    names_to = "visit",
    values_to = "bdi_score",
    names_prefix = "bdi_score_"
  ) |> 
  mutate(
    visit = replace(visit, visit=="bl", "00m")
  )
  
```

```{r}
litters_df = 
  read_csv("data/FAS_litters.csv") |> 
  janitor::clean_names() |> 
  pivot_longer(
    gd0_weight:gd18_weight,
  names_to = "gd",
  values_to = "weight"
  ) |> 
  select("litter_number", "gd", "weight") |> 
   mutate(
    gd = replace(gd, gd== "gd0_weight", "0"),
    gd = replace(gd, gd== "gd18_weight", "18"),
    gd = as.numeric(gd)
   )
```

```{r}
  litters_df_otherway =
    read_csv("data/FAS_litters.csv") |>
    janitor::clean_names() |>
    select(litter_number, ends_with("weight")) |> 
    pivot_longer(
      gd0_weight:gd18_weight,
      names_to = "gd", 
      values_to = "weight") |> 
    mutate(
      gd = case_match(
        gd,
        "gd0_weight"  ~ 0,
        "gd18_weight" ~ 18
      ))
```

## LOTR

Import LOTR words data

```{r}
fellowship_df = 
  readxl::read_excel("data/LotR_Words.xlsx", range = "B3:D6") |>
  mutate(movie = "fellowship_ring")

two_towers_df = 
  readxl::read_excel("data/LotR_Words.xlsx", range = "F3:H6") |>
  mutate(movie = "two_towers")

return_king_df = 
  readxl::read_excel("data/LotR_Words.xlsx", range = "J3:L6") |>
  mutate(movie = "return_king")

lotr_df = 
  bind_rows(fellowship_ring, two_towers, return_king) |>
  janitor::clean_names() |>
  pivot_longer(
    female:male,
    names_to = "gender", 
    values_to = "words") |> 
  relocate(movie)
```


